---
title: "week 5"
output: html_document
date: '2022-11-02'
---

```{r message=FALSE, warning=FALSE}

# packages used 
library(sf)
library(tmap)
library(tmaptools)
library(tidyverse)

```


1. Spatial joining

```{r message=FALSE, warning=FALSE}

# load london borough data, set CRS as BNG
londonboroughs <- st_read("statistical-gis-boundaries-london/ESRI/London_Borough_Excluding_MHW.shp")  %>%
  st_transform(., 27700)

# load osm data, set CRS as BNG
OSM <- st_read("greater-london-latest-free.shp/gis_osm_pois_a_free_1.shp") %>%
  st_transform(., 27700) 

# select only hotels
OSM <- OSM %>%
  filter(fclass == "hotel")

```

```{r message=FALSE, warning=FALSE}

# join the two spatial datasets
join_example <-  st_join(londonboroughs, OSM)

```

2. Static Map

Reading in more datasets

```{r message=FALSE, warning=FALSE}
# load world cities data, set CRS as BNG
world_cities <- st_read("World_Cities/World_Cities.shp") %>%
  st_transform(., 27700)
```


```{r message=FALSE, warning=FALSE}
# load airbnb csv and convert into spatial data (crs 4326)
airbnb <- read_csv("listings.csv") %>%
  st_as_sf(., coords = c("longitude", "latitude"), crs = 4326) %>% 
  # set CRS as BNG
  st_transform(., 27700) %>%
  # filter to entire homes available all year
  filter(room_type == "Entire home/apt" & availability_365 == "365")
```

2. Static Maps

```{r message=FALSE, warning=FALSE}
UK_outline <- st_read("gadm41_GBR_shp/gadm41_GBR_0.shp") %>%
  st_transform(., 27700)
```


```{r message=FALSE, warning=FALSE}
# read in the .csv and make it into spatial data

Airbnb <- read_csv("listings.csv") %>%
  st_as_sf(., coords = c("longitude", "latitude"), 
                   crs = 4326) %>%
    st_transform(., 27700)%>%
    #select entire places that are available all year
    filter(room_type == 'Entire home/apt' & availability_365 =='365')
```


```{r message=FALSE, warning=FALSE}
# make a function for the join 
# functions are covered in practical 7 but see if you can work out what is going on
# hint all you have to do is replace data1 and data2 with the data you want to use

Joinfun <- function(data1, data2){

  output<- data1%>%
  st_join(data2,.) %>%
  add_count(GSS_CODE, name="accommodation_in_borough") 

  return(output)
}

```

```{r message=FALSE, warning=FALSE}
# use the function for hotels
Hotels <- Joinfun(OSM, londonboroughs)

# then for airbnb
Airbnb <- Joinfun(Airbnb, londonboroughs)
```

```{r message=FALSE, warning=FALSE}
# subset world_cities data to UK
UK_cities <- world_cities %>%
  filter(CNTRY_NAME=='United Kingdom'&
           world_cities$CITY_NAME=='Birmingham'|
           world_cities$CITY_NAME=='London'|
           world_cities$CITY_NAME=='Edinburgh')

# set bounding box for uk
newbb <- c(xmin=-296000, ymin=5408, xmax=655696, ymax=1000000)
  
# crop uk outline according to bounding box
UK_outlinecrop <- UK_outline$geometry %>%
  st_crop(., newbb)
```

```{r message=FALSE, warning=FALSE}
# at the moment each hotel/airbnb is a row for the borough
# select one row that has number of hotels/airbnbs

Hotels <- Hotels %>%
  group_by(., GSS_CODE, NAME)%>%
  summarise(`Accomodation count` = unique(accommodation_in_borough))

Airbnb <- Airbnb %>%
  group_by(., GSS_CODE, NAME)%>%
  summarise(`Accomodation count` = unique(accommodation_in_borough))
```

```{r message=FALSE, warning=FALSE}
tmap_mode("plot")

# set the breaks
# for our mapped data
breaks = c(0, 5, 12, 26, 57, 286) 

# plot each map
tm1 <- tm_shape(Hotels) + 
  tm_polygons("Accomodation count", 
              breaks=breaks,
              palette="PuBu")+
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(a)", position=c(0,0.85), size=1.5)

tm2 <- tm_shape(Airbnb) + 
  tm_polygons("Accomodation count",
              breaks=breaks, 
              palette="PuBu") + 
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(b)", position=c(0,0.85), size=1.5)

tm3 <- tm_shape(UK_outlinecrop)+ 
  tm_polygons(col="darkslategray1")+
  tm_layout(frame=FALSE)+
  tm_shape(UK_cities) +
  tm_symbols(col = "red", scale = .5)+
  tm_text("CITY_NAME", xmod=-1, ymod=-0.5)

legend <- tm_shape(Hotels) +
    tm_polygons("Accomodation count",
                palette="PuBu") +
    tm_scale_bar(position=c(0.2,0.04), text.size=0.6)+
    tm_compass(north=0, position=c(0.65,0.6))+
    tm_layout(legend.only = TRUE, legend.position=c(0.2,0.25),asp=0.1)+
    tm_credits("(c) OpenStreetMap contrbutors and Air b n b", position=c(0.0,0.0))
  
t=tmap_arrange(tm1, tm2, tm3, legend, ncol=2)

t
```

3. Inset map

```{r message=FALSE, warning=FALSE}

Londonbb <- st_bbox(Airbnb,
                    crs = st_crs(Airbnb))%>%
  # need this to convert it into a class of sf
  # otherwise bb won't have a class it will just be x and y coordinates for the box
  # this makes it into a polygon
  st_as_sfc()

```

```{r}
main <- tm_shape(Airbnb, bbbox = Londonbb) + 
  tm_polygons("Accomodation count",
              breaks=breaks, 
              palette="PuBu")+
  tm_scale_bar(position = c("left", "bottom"), text.size = .75)+
  tm_layout(legend.position = c("right","top"), 
            legend.text.size=.75, 
            legend.title.size = 1.1,
            frame=FALSE)+
  tm_credits("(c) OpenStreetMap contrbutors and Air b n b", position=c(0.0,0.0))+
  #tm_text(text = "NAME", size = .5, along.lines =T, remove.overlap=T,  auto.placement=F)+
  tm_compass(type = "8star", position = c(0.06, 0.1)) +

  #bottom left top right
  tm_layout(inner.margin=c(0.02,0.02,0.02,0.2))
```

```{r message=FALSE, warning=FALSE}
inset = tm_shape(UK_outlinecrop) + tm_polygons() +
  tm_shape(Londonbb)+ 
  tm_borders(col = "grey40", lwd = 3)+
    tm_layout(frame=FALSE,
            bg.color = "transparent")+
  tm_shape(UK_cities) +
  tm_symbols(col = "red", scale = .5)+
  tm_text("CITY_NAME", xmod=-1.5, ymod=-0.5)
```

```{r}
library(grid)
main
print(inset, vp = viewport(0.86, 0.29, width = 0.5, height = 0.55))
```

4. Export
```{r}
tmap_save(t, 'hotelsandairbnbR.png')

library(grid)
tmap_save(main,insets_tm = inset,insets_vp=viewport(x=0.86, y=0.29, width=.5, height=.55), filename="test.pdf", dpi=600)
```

5. Basic Interactive Map
```{r message=FALSE, warning=FALSE}
tmap_mode("view")

tm_shape(Airbnb) + 
  tm_polygons("Accomodation count", breaks=breaks) 
```

```{r}
# library for pop up boxes
library(leafpop)
library(leaflet)

#join data
Joined <- Airbnb%>%
  st_join(., Hotels, join = st_equals)%>%
  dplyr::select(GSS_CODE.x, NAME.x, `Accomodation count.x`, `Accomodation count.y`)%>%
  dplyr::rename(`GSS code` =`GSS_CODE.x`,
                `Borough` = `NAME.x`,
                `Airbnb count` = `Accomodation count.x`,
                `Hotel count`= `Accomodation count.y`)%>%
  st_transform(., 4326)
  
  
#remove the geometry for our pop up boxes to avoid
popupairbnb <-Joined %>%
  st_drop_geometry()%>%
  dplyr::select(`Airbnb count`, Borough)%>%
  popupTable()

popuphotel <-Joined %>%
  st_drop_geometry()%>%
  dplyr::select(`Hotel count`, Borough)%>%
  popupTable()

tmap_mode("view")

# set the colour palettes using our previously defined breaks


pal1 <- Joined %>%
  colorBin(palette = "YlOrRd", domain=.$`Airbnb count`, bins=breaks)

pal1 <-colorBin(palette = "YlOrRd", domain=Joined$`Airbnb count`, bins=breaks)

pal2 <- Joined %>%
  colorBin(palette = "YlOrRd", domain=.$`Hotel count`, bins=breaks)


map<- leaflet(Joined) %>%
  # add basemap options
  addTiles(group = "OSM (default)") %>%
  addProviderTiles(providers$Stamen.Toner, group = "Toner") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB")%>%
  
  #add our polygons, linking to the tables we just made
  addPolygons(color="white", 
              weight = 2,
              opacity = 1,
              dashArray = "3",
              popup = popupairbnb,
              fillOpacity = 0.7,
              fillColor = ~pal2(`Airbnb count`),
              group = "Airbnb")%>%
  
  addPolygons(fillColor = ~pal2(`Hotel count`), 
              weight = 2,
              opacity = 1,
              color = "white",
              dashArray = "3",
              popup = popupairbnb,
              fillOpacity = 0.7,group = "Hotels")%>%
  # add a legend
  addLegend(pal = pal2, values = ~`Hotel count`, group = c("Airbnb","Hotel"), 
            position ="bottomleft", title = "Accomodation count") %>%
  # specify layers control
  addLayersControl(
    baseGroups = c("OSM (default)", "Toner", "Toner Lite", "CartoDB"),
    overlayGroups = c("Airbnb", "Hotels"),
    options = layersControlOptions(collapsed = FALSE)
  )

# plot the map
map
```


